# https://taskfile.dev

version: '3'

tasks:
  client:
    dir: client
    cmds:
      - elm make --output=srv/elm.js --optimize src/Main.elm
    sources:
      - src/*
    generates:
      - public/elm.js

  # srv:
  #   cmds:
  #     - python -m http.server --bind 127.0.0.1 --directory srv
