# https://taskfile.dev
---
version: '3'

includes:
  server:
    taskfile: ./server
    dir: ./server

  client:
    taskfile: ./client
    dir: ./client

tasks:
  default:
    - task: client:default
    - task: server:default

  dev:
    - task: client:dev
    - task: server:dev
