---
version: '3'

tasks:
  default:
    - task: test
    - task: staticcheck
    - task: build

  test:
    cmds:
      - go test ./...
    sources:
      - main.go
      - pkg/**/*.go

  staticcheck:
    cmds:
      - staticcheck -checks all ./...
    sources:
      - main.go
      - pkg/**/*.go

  build:
    cmds:
      - go build
    sources:
      - main.go
      - pkg/**/*.go
    generates:
      - server
